import MainHeader from "@/components/MainHeader";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

export const metadata = {
  title: "Nicolax | developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background text-darkAccent overflow-x-hidden`}
      >
        <MainHeader />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
