import MainHeader from "@/components/MainHeader";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-accent text-white overflow-x-hidden`}
      >
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
